name: Build and publish docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.3.0
      - name: Build image
        run: docker build -t dota-tournament-bot .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Login to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run: docker tag dota-tournament-bot registry.digitalocean.com/${{secrets.DO_REGISTRY_NAME}}/dota-tournament-bot:${{github.event.inputs.version}}
      - name: Push to DO Container Registry
        run: docker push registry.digitalocean.com/${{secrets.DO_REGISTRY_NAME}}/dota-tournament-bot:${{github.event.inputs.version}}
